export const LOAD_CALENDARS = 'LOAD_CALENDARS';
export const LOAD_CALENDARS_SUCCESS = 'LOAD_CALENDARS_SUCCESS';

export const LOAD_CALENDAR = 'LOAD_CALENDAR';
export const LOAD_CALENDAR_SUCCESS = 'LOAD_CALENDAR_SUCCESS';

export const OPEN_EVENTDETAILS = 'OPEN_EVENTDETAILS';
export const CLOSE_EVENTDETAILS = 'CLOSE_EVENTDETAILS';
