export const LOAD_CALENDARS = 'LOAD_CALENDARS';
export const LOAD_CALENDARS_SUCCESS = 'LOAD_CALENDARS_SUCCESS';

export const LOAD_CALENDAR = 'LOAD_CALENDAR';
export const LOAD_CALENDAR_SUCCESS = 'LOAD_CALENDAR_SUCCESS';
